### PR TITLE
Fix #10

### LINKED ISSUE #10: Invariant Violation: "border" is not a valid style property
With React 16, a `Invariant Violation: "border" is not a valid style property` error is shown on the console:
https://github.com/react-native-web-community/react-native-web-webview/blob/bc1962b1d780f809c75bfa100ed52d50a094c4e0/src/index.js#L124
Seems the valid border values are

```
      "borderBottomColor",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
      "borderBottomWidth",
      "borderColor",
      "borderLeftColor",
      "borderLeftWidth",
      "borderRadius",
      "borderRightColor",
      "borderRightWidth",
      "borderStyle",
      "borderTopColor",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderTopWidth",
      "borderWidth`
```

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by piranna** [comment]
> Thanks!

You are welcome :-)

**Comment by piranna** [comment]
Can this be published to npm? Or is it better to wait until we fix the thing with the files extensions?

**Comment by Minishlink** [comment]
Sure, sorry! v2.2.3

**Comment by piranna** [comment]
Thqank you! :-D

**Pull request merged**
