### PR TITLE
Create index.android.js

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by Minishlink** [comment]
I'd be happy to merge this, but I'm curious what's your use case for this? We're going full circle ^^

**Comment by piranna** [comment]
I quickly did it from the website :-P The idea here is that by using `react-native-web-webview` module, it will use native implementations for mobile platforms due to the usage of the special `.android.js` and `.ios.js` extensions (and the same for `.web.js` for web platform, by the way).

**Comment by Minishlink** [comment]
Hey, sorry for the delay :)
So you import directly from `react-native-web-webview`? Why not alias `WebView` to `react-native-web-webview` in the Webpack config?

**Comment by piranna** [comment]
> Why not alias WebView to react-native-web-webview in the Webpack config?

Didn't know about that option... On the other hand, doing it on this repo makes it transparent for the users.

**Comment by Minishlink** [comment]
Yes, I got your point. Can you try if a single `index.native.js` works?

**Comment by piranna** [comment]
Does the `.native.js` extension exists? I have not seen it anywhere... The most alike is to use `.js` (without a platform) as a default fallback, it would be another option...

**Comment by Minishlink** [comment]
Saw this in https://github.com/godaddy/svgs the other day, but not sure if it actually works :)

**Comment by piranna** [comment]
Sorry for the delay, busy with other things.

I've investigated a little bit regarding this and seems the only recognized extensions are `.android.js` and `.web.js`. On https://stackoverflow.com/a/46563266/586382 it shows how to use the `Platform` object too, and at https://facebook.github.io/react-native/docs/platform-specific-code.html is shown with more detail including the extension thing, that it's being used on the `react-native` code too (https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.android.js and https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.ios.js), but seems they are the only ones that can identify, also there`s no references to `.native.js` at all. Seems that the `.web.js` one is a sort of hack that people add to their `webpack.js` file, so maybe it would be a better alternative to rename current `index.js` to `index.web.js` and add a new `index.js` file that use the native code, how do you see it?

By the way, how could I be able to override a single class on `webpack.js` to use a different module as you suggested before? I'm having a similar problem with https://github.com/react-native-community/react-native-drawer-layout :-)

**Comment by Minishlink** [comment]
It should be `index.js` as the default for this library, because it's the library's **main** target. I'd like to say that it's the **only** target and not add `index.android.js` and `index.ios.js` but let's see if we can solve your problem first. If not we'll merge this PR and the other ;)

Can you take a look at one of my app's webpack config : https://github.com/Minishlink/DailyScrum/blob/staging/web/webpack.config.babel.js#L111 Here, if I wanted to use WebView in this app, I'd add a `WebView: 'react-native-web-webview'`.  And in my JS code I'd import from `WebView`. This is resolved on the web thanks to the alias you just added, and for Android and iOS, it is resolved thanks to the `@providesModule` (which is present in every components of React Native)

**Pull request closed without merging**
